FROM node:12-alpine

EXPOSE 8080 
WORKDIR /app-back

COPY app-back/package.json /app-back/package.json
COPY app-back/package-lock.json /app-back/package-lock.json

RUN npm install
COPY ./app-back /app-back
# Run 'npm run dev' when the container starts.
CMD ["npm", "run", "start"]