FROM node:17-alpine

ENV PORT=8080
EXPOSE 8080
RUN mkdir -p /app-front/public /app-front/src
WORKDIR /app-front
COPY app-front/tsconfig.json /app-front/tsconfig.json
#COPY tslint.json /app/tslint.json JE SAIS PAS SI JE LE MET
COPY app-front/package.json /app-front/package.json
COPY app-front/package-lock.json /app-front/package-lock.json

RUN npm install
RUN npm install react-scripts
# Run 'npm run dev' when the container starts.
CMD ["npm", "run", "start"]