version: '3'
services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgresql/data/${DB_NAME}:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

  postgres-test:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_TEST_USER}
      - POSTGRES_PASSWORD=${DB_TEST_PWD}
      - POSTGRES_DB=${DB_TEST_NAME}
    volumes:
      - ./postgresql/data/${DB_TEST_NAME}:/var/lib/postgresql/data
    ports:
      - "${DB_TEST_PORT}:${DB_PORT}"

  app-back:
    build:
      context: '.'
      dockerfile: Dockerfile.nest
    volumes:
      - './app-back:/app-back:rw,cached'
    ports:
      - '${NEST_PORT}:${NEST_PORT}'
    command: 'npm run start:dev'
    links:
      - postgres
      - postgres-test
    depends_on:
      - postgres
      - postgres-test

  app-front:
    build:
      context: '.'
      dockerfile: Dockerfile.react
    volumes:
      - /app-front/node_modules
      - ./app-front:/app-front
    ports:
      - '${REACT_PORT}:${REACT_PORT}'
    command: 'npm run start'