runtime: nodejs12
instance_class: F1
entrypoint: 'node dist/main.js'

env_variables:
  NODE_PATH: 'dist'
  NODE_ENV: 'prod'

  # JWT configuration
  JWT_ISSUER: 'DOCKERIZE'
  JWT_TTL: '12h'
  JWT_PRIVATE_KEY: {{ $JWT_PRIVATE_KEY }}
  JWT_PUBLIC_KEY: {{ $JWT_PUBLIC_KEY }}

  # Database configuration
  TYPEORM_CONNECTION: ''
  TYPEORM_HOST: ''
  TYPEORM_INSTANCE_CONNECTION_NAME: ''
  TYPEORM_USERNAME: ''
  TYPEORM_PASSWORD: ''
  TYPEORM_DATABASE: ''
  TYPEORM_PORT: ''
  TYPEORM_ENTITIES: 'dist/**/*.model.js'
