name: Docker Compose Actions Workflow
on: push
jobs:
  back-build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./packages/backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install node modules
        run: npm install
      - name: Build nestJS back
        run: npm run build

  front-build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./packages/frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install node modules
        run: npm install
      - name: Build React front
        run: npm run build
